# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_main(object):
    def setupUi(self, Frame_main):
        Frame_main.setObjectName("Frame_main")
        Frame_main.resize(748, 477)
        Frame_main.setMinimumSize(QtCore.QSize(728, 386))
        Frame_main.setMaximumSize(QtCore.QSize(16777215, 999999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame_main.setWindowIcon(icon)
        Frame_main.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Frame_main)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 20, 20))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icon/ship.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.tv_shipNum = QtWidgets.QLabel(self.groupBox)
        self.tv_shipNum.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.tv_shipNum.setObjectName("tv_shipNum")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(100, 10, 21, 21))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("icon/oil.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.tv_oil = QtWidgets.QLabel(self.groupBox)
        self.tv_oil.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.tv_oil.setObjectName("tv_oil")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(190, 10, 21, 21))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("icon/ammo.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.tv_ammo = QtWidgets.QLabel(self.groupBox)
        self.tv_ammo.setGeometry(QtCore.QRect(220, 10, 72, 21))
        self.tv_ammo.setObjectName("tv_ammo")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(280, 10, 21, 21))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icon/steel.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.tv_steel = QtWidgets.QLabel(self.groupBox)
        self.tv_steel.setGeometry(QtCore.QRect(310, 10, 61, 21))
        self.tv_steel.setObjectName("tv_steel")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("icon/aluminium.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.tv_aluminium = QtWidgets.QLabel(self.groupBox)
        self.tv_aluminium.setGeometry(QtCore.QRect(400, 10, 41, 21))
        self.tv_aluminium.setObjectName("tv_aluminium")
        self.tv_oilChange = QtWidgets.QLabel(self.groupBox)
        self.tv_oilChange.setGeometry(QtCore.QRect(130, 30, 51, 16))
        self.tv_oilChange.setText("")
        self.tv_oilChange.setObjectName("tv_oilChange")
        self.tv_ammoChange = QtWidgets.QLabel(self.groupBox)
        self.tv_ammoChange.setGeometry(QtCore.QRect(220, 30, 72, 15))
        self.tv_ammoChange.setText("")
        self.tv_ammoChange.setObjectName("tv_ammoChange")
        self.tv_steelChange = QtWidgets.QLabel(self.groupBox)
        self.tv_steelChange.setGeometry(QtCore.QRect(310, 30, 72, 15))
        self.tv_steelChange.setText("")
        self.tv_steelChange.setObjectName("tv_steelChange")
        self.tv_aluminiumChange = QtWidgets.QLabel(self.groupBox)
        self.tv_aluminiumChange.setGeometry(QtCore.QRect(400, 30, 41, 16))
        self.tv_aluminiumChange.setText("")
        self.tv_aluminiumChange.setObjectName("tv_aluminiumChange")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(460, 10, 16, 21))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("icon/p541.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.tv_fastRepair = QtWidgets.QLabel(self.groupBox)
        self.tv_fastRepair.setGeometry(QtCore.QRect(480, 10, 31, 21))
        self.tv_fastRepair.setObjectName("tv_fastRepair")
        self.tv_fastRepairChange = QtWidgets.QLabel(self.groupBox)
        self.tv_fastRepairChange.setGeometry(QtCore.QRect(480, 30, 51, 16))
        self.tv_fastRepairChange.setText("")
        self.tv_fastRepairChange.setObjectName("tv_fastRepairChange")
        self.sw_mian = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_mian.setGeometry(QtCore.QRect(10, 60, 741, 401))
        self.sw_mian.setObjectName("sw_mian")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 261, 381))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tv_fleetName = QtWidgets.QLabel(self.groupBox_2)
        self.tv_fleetName.setGeometry(QtCore.QRect(10, 60, 251, 31))
        self.tv_fleetName.setObjectName("tv_fleetName")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 41, 71, 20))
        self.label_22.setObjectName("label_22")
        self.tv_nowrw = QtWidgets.QLabel(self.groupBox_2)
        self.tv_nowrw.setGeometry(QtCore.QRect(60, 41, 191, 20))
        self.tv_nowrw.setMouseTracking(True)
        self.tv_nowrw.setFrameShape(QtWidgets.QFrame.Box)
        self.tv_nowrw.setObjectName("tv_nowrw")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 41, 25))
        self.label_23.setObjectName("label_23")
        self.bt_add_campaign = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_add_campaign.setGeometry(QtCore.QRect(190, 10, 61, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/yx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_add_campaign.setIcon(icon1)
        self.bt_add_campaign.setObjectName("bt_add_campaign")
        self.bt_add_pvp = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_add_pvp.setGeometry(QtCore.QRect(120, 10, 61, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_add_pvp.setIcon(icon2)
        self.bt_add_pvp.setObjectName("bt_add_pvp")
        self.bt_add_battle = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_add_battle.setGeometry(QtCore.QRect(50, 10, 61, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/boat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_add_battle.setIcon(icon3)
        self.bt_add_battle.setObjectName("bt_add_battle")
        self.lt_our = QtWidgets.QListWidget(self.groupBox_2)
        self.lt_our.setGeometry(QtCore.QRect(10, 90, 151, 281))
        self.lt_our.setObjectName("lt_our")
        self.lt_our_2 = QtWidgets.QListWidget(self.groupBox_2)
        self.lt_our_2.setGeometry(QtCore.QRect(160, 90, 101, 281))
        self.lt_our_2.setObjectName("lt_our_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(270, 0, 461, 391))
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lt_rw = QtWidgets.QListWidget(self.tab)
        self.lt_rw.setGeometry(QtCore.QRect(0, 10, 301, 351))
        self.lt_rw.setObjectName("lt_rw")
        self.bt_rw_up = QtWidgets.QPushButton(self.tab)
        self.bt_rw_up.setGeometry(QtCore.QRect(240, 330, 21, 21))
        self.bt_rw_up.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_rw_up.setIcon(icon4)
        self.bt_rw_up.setObjectName("bt_rw_up")
        self.bt_rw_del = QtWidgets.QPushButton(self.tab)
        self.bt_rw_del.setGeometry(QtCore.QRect(260, 330, 21, 21))
        self.bt_rw_del.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_rw_del.setIcon(icon5)
        self.bt_rw_del.setObjectName("bt_rw_del")
        self.lt_rw_detail = QtWidgets.QListWidget(self.tab)
        self.lt_rw_detail.setGeometry(QtCore.QRect(300, 10, 151, 351))
        self.lt_rw_detail.setObjectName("lt_rw_detail")
        self.cb_run = QtWidgets.QCheckBox(self.tab)
        self.cb_run.setGeometry(QtCore.QRect(310, 330, 131, 21))
        self.cb_run.setObjectName("cb_run")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tv_nowDeal = QtWidgets.QLabel(self.tab_2)
        self.tv_nowDeal.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.tv_nowDeal.setObjectName("tv_nowDeal")
        self.af = QtWidgets.QTabWidget(self.tab_2)
        self.af.setGeometry(QtCore.QRect(0, 20, 501, 391))
        self.af.setObjectName("af")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lt_log_classical = QtWidgets.QListWidget(self.tab_5)
        self.lt_log_classical.setGeometry(QtCore.QRect(0, 0, 451, 321))
        self.lt_log_classical.setObjectName("lt_log_classical")
        self.af.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.lt_log_imp = QtWidgets.QListWidget(self.tab_6)
        self.lt_log_imp.setGeometry(QtCore.QRect(0, 0, 451, 321))
        self.lt_log_imp.setObjectName("lt_log_imp")
        self.af.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.lt_log_detail = QtWidgets.QListWidget(self.tab_7)
        self.lt_log_detail.setGeometry(QtCore.QRect(0, 0, 451, 321))
        self.lt_log_detail.setObjectName("lt_log_detail")
        self.bt_getLog = QtWidgets.QPushButton(self.tab_7)
        self.bt_getLog.setGeometry(QtCore.QRect(370, 280, 61, 23))
        self.bt_getLog.setObjectName("bt_getLog")
        self.af.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 40, 441, 321))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tb_count = QtWidgets.QTableWidget(self.groupBox_5)
        self.tb_count.setGeometry(QtCore.QRect(10, 20, 431, 291))
        self.tb_count.setObjectName("tb_count")
        self.tb_count.setColumnCount(4)
        self.tb_count.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_count.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_count.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_count.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_count.setHorizontalHeaderItem(3, item)
        self.bt_count_ship = QtWidgets.QPushButton(self.tab_3)
        self.bt_count_ship.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.bt_count_ship.setObjectName("bt_count_ship")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.groupBox_19.setObjectName("groupBox_19")
        self.cb_repair = QtWidgets.QComboBox(self.groupBox_19)
        self.cb_repair.setGeometry(QtCore.QRect(40, 20, 111, 22))
        self.cb_repair.setObjectName("cb_repair")
        self.cb_repair.addItem("")
        self.cb_repair.addItem("")
        self.cb_repair.addItem("")
        self.cb_repair.addItem("")
        self.cb_rank = QtWidgets.QCheckBox(self.groupBox_19)
        self.cb_rank.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.cb_rank.setChecked(True)
        self.cb_rank.setObjectName("cb_rank")
        self.cb_500stop = QtWidgets.QCheckBox(self.groupBox_19)
        self.cb_500stop.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.cb_500stop.setChecked(True)
        self.cb_500stop.setObjectName("cb_500stop")
        self.label_4 = QtWidgets.QLabel(self.groupBox_19)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 161, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cb_free_explore = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_free_explore.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.cb_free_explore.setChecked(True)
        self.cb_free_explore.setObjectName("cb_free_explore")
        self.cb_free_shower = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_free_shower.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.cb_free_shower.setObjectName("cb_free_shower")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 161, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cb_changeName = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_changeName.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.cb_changeName.setChecked(True)
        self.cb_changeName.setObjectName("cb_changeName")
        self.tabWidget.addTab(self.tab_4, "")
        self.sw_mian.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 10, 731, 381))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.cb_dismantle = QtWidgets.QGroupBox(self.groupBox_9)
        self.cb_dismantle.setGeometry(QtCore.QRect(10, 10, 231, 361))
        self.cb_dismantle.setCheckable(True)
        self.cb_dismantle.setObjectName("cb_dismantle")
        self.cb_d_dd = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_dd.setGeometry(QtCore.QRect(10, 30, 61, 19))
        self.cb_d_dd.setCheckable(True)
        self.cb_d_dd.setChecked(True)
        self.cb_d_dd.setObjectName("cb_d_dd")
        self.cb_d_cl = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_cl.setGeometry(QtCore.QRect(70, 30, 61, 19))
        self.cb_d_cl.setChecked(True)
        self.cb_d_cl.setObjectName("cb_d_cl")
        self.cb_d_ca = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_ca.setGeometry(QtCore.QRect(130, 30, 61, 19))
        self.cb_d_ca.setChecked(True)
        self.cb_d_ca.setAutoRepeat(False)
        self.cb_d_ca.setObjectName("cb_d_ca")
        self.cb_d_bb = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_bb.setGeometry(QtCore.QRect(10, 60, 61, 19))
        self.cb_d_bb.setChecked(False)
        self.cb_d_bb.setObjectName("cb_d_bb")
        self.cb_d_bc = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_bc.setGeometry(QtCore.QRect(70, 60, 61, 19))
        self.cb_d_bc.setObjectName("cb_d_bc")
        self.cb_d_cvl = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_cvl.setGeometry(QtCore.QRect(130, 60, 61, 19))
        self.cb_d_cvl.setObjectName("cb_d_cvl")
        self.cb_d_cv = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_cv.setGeometry(QtCore.QRect(10, 90, 61, 19))
        self.cb_d_cv.setObjectName("cb_d_cv")
        self.cb_d_equipment = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_equipment.setGeometry(QtCore.QRect(100, 120, 91, 21))
        self.cb_d_equipment.setObjectName("cb_d_equipment")
        self.cb_d_save = QtWidgets.QComboBox(self.cb_dismantle)
        self.cb_d_save.setGeometry(QtCore.QRect(10, 120, 87, 22))
        self.cb_d_save.setObjectName("cb_d_save")
        self.cb_d_save.addItem("")
        self.cb_d_save.addItem("")
        self.cb_d_save.addItem("")
        self.cb_d_save.addItem("")
        self.cb_d_save.addItem("")
        self.cb_d_unusualShip = QtWidgets.QCheckBox(self.cb_dismantle)
        self.cb_d_unusualShip.setGeometry(QtCore.QRect(10, 150, 121, 19))
        self.cb_d_unusualShip.setObjectName("cb_d_unusualShip")
        self.ed_d_unusualShip = QtWidgets.QLineEdit(self.cb_dismantle)
        self.ed_d_unusualShip.setGeometry(QtCore.QRect(10, 170, 211, 21))
        self.ed_d_unusualShip.setObjectName("ed_d_unusualShip")
        self.label_5 = QtWidgets.QLabel(self.cb_dismantle)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 211, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.cb_dismantle)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 211, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.cb_dismantle)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 181, 16))
        self.label_9.setObjectName("label_9")
        self.cb_strengthen = QtWidgets.QGroupBox(self.groupBox_9)
        self.cb_strengthen.setGeometry(QtCore.QRect(250, 10, 411, 361))
        self.cb_strengthen.setCheckable(True)
        self.cb_strengthen.setObjectName("cb_strengthen")
        self.label = QtWidgets.QLabel(self.cb_strengthen)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.lt_qh_ship_list = QtWidgets.QListWidget(self.cb_strengthen)
        self.lt_qh_ship_list.setGeometry(QtCore.QRect(10, 40, 391, 171))
        self.lt_qh_ship_list.setObjectName("lt_qh_ship_list")
        self.cb_s_f = QtWidgets.QCheckBox(self.cb_strengthen)
        self.cb_s_f.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.cb_s_f.setChecked(True)
        self.cb_s_f.setObjectName("cb_s_f")
        self.cb_s_t = QtWidgets.QCheckBox(self.cb_strengthen)
        self.cb_s_t.setGeometry(QtCore.QRect(80, 230, 71, 16))
        self.cb_s_t.setChecked(True)
        self.cb_s_t.setObjectName("cb_s_t")
        self.cb_s_d = QtWidgets.QCheckBox(self.cb_strengthen)
        self.cb_s_d.setGeometry(QtCore.QRect(150, 230, 71, 16))
        self.cb_s_d.setChecked(True)
        self.cb_s_d.setObjectName("cb_s_d")
        self.cb_s_a = QtWidgets.QCheckBox(self.cb_strengthen)
        self.cb_s_a.setGeometry(QtCore.QRect(220, 230, 51, 16))
        self.cb_s_a.setChecked(True)
        self.cb_s_a.setObjectName("cb_s_a")
        self.cb_s_unusualShip = QtWidgets.QCheckBox(self.cb_strengthen)
        self.cb_s_unusualShip.setGeometry(QtCore.QRect(120, 260, 121, 21))
        self.cb_s_unusualShip.setObjectName("cb_s_unusualShip")
        self.label_11 = QtWidgets.QLabel(self.cb_strengthen)
        self.label_11.setGeometry(QtCore.QRect(240, 260, 211, 21))
        self.label_11.setObjectName("label_11")
        self.cb_s_save = QtWidgets.QComboBox(self.cb_strengthen)
        self.cb_s_save.setGeometry(QtCore.QRect(10, 260, 87, 22))
        self.cb_s_save.setObjectName("cb_s_save")
        self.cb_s_save.addItem("")
        self.cb_s_save.addItem("")
        self.cb_s_save.addItem("")
        self.cb_s_save.addItem("")
        self.cb_s_save.addItem("")
        self.ed_s_unusualShip = QtWidgets.QLineEdit(self.cb_strengthen)
        self.ed_s_unusualShip.setGeometry(QtCore.QRect(10, 290, 391, 21))
        self.ed_s_unusualShip.setObjectName("ed_s_unusualShip")
        self.bt_add_qh = QtWidgets.QPushButton(self.cb_strengthen)
        self.bt_add_qh.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.bt_add_qh.setObjectName("bt_add_qh")
        self.bt_d_back = QtWidgets.QPushButton(self.groupBox_9)
        self.bt_d_back.setGeometry(QtCore.QRect(670, 340, 61, 28))
        self.bt_d_back.setObjectName("bt_d_back")
        self.sw_mian.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.groupBox_18 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 10, 731, 381))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.cb_build = QtWidgets.QGroupBox(self.groupBox_18)
        self.cb_build.setGeometry(QtCore.QRect(10, 0, 211, 371))
        self.cb_build.setFlat(False)
        self.cb_build.setCheckable(True)
        self.cb_build.setChecked(False)
        self.cb_build.setObjectName("cb_build")
        self.label_26 = QtWidgets.QLabel(self.cb_build)
        self.label_26.setGeometry(QtCore.QRect(10, 120, 201, 16))
        self.label_26.setObjectName("label_26")
        self.ed_build_unusual = QtWidgets.QLineEdit(self.cb_build)
        self.ed_build_unusual.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.ed_build_unusual.setObjectName("ed_build_unusual")
        self.label_27 = QtWidgets.QLabel(self.cb_build)
        self.label_27.setGeometry(QtCore.QRect(10, 136, 201, 16))
        self.label_27.setObjectName("label_27")
        self.cb_build_unusual = QtWidgets.QCheckBox(self.cb_build)
        self.cb_build_unusual.setGeometry(QtCore.QRect(10, 80, 141, 19))
        self.cb_build_unusual.setObjectName("cb_build_unusual")
        self.label_28 = QtWidgets.QLabel(self.cb_build)
        self.label_28.setGeometry(QtCore.QRect(10, 22, 21, 20))
        self.label_28.setObjectName("label_28")
        self.ed_build_o = QtWidgets.QSpinBox(self.cb_build)
        self.ed_build_o.setGeometry(QtCore.QRect(30, 20, 46, 22))
        self.ed_build_o.setMinimum(30)
        self.ed_build_o.setMaximum(999)
        self.ed_build_o.setObjectName("ed_build_o")
        self.ed_build_ammo = QtWidgets.QSpinBox(self.cb_build)
        self.ed_build_ammo.setGeometry(QtCore.QRect(120, 18, 46, 22))
        self.ed_build_ammo.setMinimum(30)
        self.ed_build_ammo.setMaximum(999)
        self.ed_build_ammo.setObjectName("ed_build_ammo")
        self.label_29 = QtWidgets.QLabel(self.cb_build)
        self.label_29.setGeometry(QtCore.QRect(100, 20, 21, 20))
        self.label_29.setObjectName("label_29")
        self.ed_build_s = QtWidgets.QSpinBox(self.cb_build)
        self.ed_build_s.setGeometry(QtCore.QRect(30, 48, 46, 22))
        self.ed_build_s.setMinimum(30)
        self.ed_build_s.setMaximum(999)
        self.ed_build_s.setObjectName("ed_build_s")
        self.label_30 = QtWidgets.QLabel(self.cb_build)
        self.label_30.setGeometry(QtCore.QRect(10, 50, 21, 20))
        self.label_30.setObjectName("label_30")
        self.ed_build_al = QtWidgets.QSpinBox(self.cb_build)
        self.ed_build_al.setGeometry(QtCore.QRect(120, 48, 46, 22))
        self.ed_build_al.setMinimum(30)
        self.ed_build_al.setMaximum(999)
        self.ed_build_al.setObjectName("ed_build_al")
        self.label_32 = QtWidgets.QLabel(self.cb_build)
        self.label_32.setGeometry(QtCore.QRect(100, 50, 21, 20))
        self.label_32.setObjectName("label_32")
        self.lt_build = QtWidgets.QListWidget(self.cb_build)
        self.lt_build.setGeometry(QtCore.QRect(10, 180, 191, 141))
        self.lt_build.setObjectName("lt_build")
        self.cb_build_time = QtWidgets.QCheckBox(self.cb_build)
        self.cb_build_time.setGeometry(QtCore.QRect(10, 154, 61, 20))
        self.cb_build_time.setObjectName("cb_build_time")
        self.label_24 = QtWidgets.QLabel(self.cb_build)
        self.label_24.setGeometry(QtCore.QRect(120, 153, 81, 20))
        self.label_24.setObjectName("label_24")
        self.ed_time = QtWidgets.QDoubleSpinBox(self.cb_build)
        self.ed_time.setGeometry(QtCore.QRect(60, 152, 61, 21))
        self.ed_time.setObjectName("ed_time")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_21.setGeometry(QtCore.QRect(230, 0, 211, 371))
        self.groupBox_21.setObjectName("groupBox_21")
        self.cb_eq = QtWidgets.QCheckBox(self.groupBox_21)
        self.cb_eq.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.cb_eq.setObjectName("cb_eq")
        self.ed_eq_time = QtWidgets.QTimeEdit(self.groupBox_21)
        self.ed_eq_time.setGeometry(QtCore.QRect(60, 173, 61, 20))
        self.ed_eq_time.setObjectName("ed_eq_time")
        self.cb_eq_unusual = QtWidgets.QCheckBox(self.groupBox_21)
        self.cb_eq_unusual.setGeometry(QtCore.QRect(10, 100, 141, 19))
        self.cb_eq_unusual.setObjectName("cb_eq_unusual")
        self.label_33 = QtWidgets.QLabel(self.groupBox_21)
        self.label_33.setGeometry(QtCore.QRect(120, 173, 72, 20))
        self.label_33.setObjectName("label_33")
        self.lt_eq = QtWidgets.QListWidget(self.groupBox_21)
        self.lt_eq.setGeometry(QtCore.QRect(10, 200, 191, 121))
        self.lt_eq.setObjectName("lt_eq")
        self.cb_eq_ammo = QtWidgets.QSpinBox(self.groupBox_21)
        self.cb_eq_ammo.setGeometry(QtCore.QRect(120, 38, 46, 22))
        self.cb_eq_ammo.setMinimum(30)
        self.cb_eq_ammo.setMaximum(999)
        self.cb_eq_ammo.setObjectName("cb_eq_ammo")
        self.cb_eq_time = QtWidgets.QCheckBox(self.groupBox_21)
        self.cb_eq_time.setGeometry(QtCore.QRect(10, 174, 51, 20))
        self.cb_eq_time.setObjectName("cb_eq_time")
        self.cb_eq_s = QtWidgets.QSpinBox(self.groupBox_21)
        self.cb_eq_s.setGeometry(QtCore.QRect(30, 68, 46, 22))
        self.cb_eq_s.setMinimum(30)
        self.cb_eq_s.setMaximum(999)
        self.cb_eq_s.setObjectName("cb_eq_s")
        self.label_34 = QtWidgets.QLabel(self.groupBox_21)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 21, 20))
        self.label_34.setObjectName("label_34")
        self.cb_eq_al = QtWidgets.QSpinBox(self.groupBox_21)
        self.cb_eq_al.setGeometry(QtCore.QRect(120, 68, 46, 22))
        self.cb_eq_al.setMinimum(30)
        self.cb_eq_al.setMaximum(999)
        self.cb_eq_al.setObjectName("cb_eq_al")
        self.cb_eq_o = QtWidgets.QSpinBox(self.groupBox_21)
        self.cb_eq_o.setGeometry(QtCore.QRect(30, 40, 46, 22))
        self.cb_eq_o.setMinimum(30)
        self.cb_eq_o.setMaximum(999)
        self.cb_eq_o.setObjectName("cb_eq_o")
        self.label_35 = QtWidgets.QLabel(self.groupBox_21)
        self.label_35.setGeometry(QtCore.QRect(100, 40, 21, 20))
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.groupBox_21)
        self.label_37.setGeometry(QtCore.QRect(10, 156, 201, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_21)
        self.label_38.setGeometry(QtCore.QRect(100, 70, 21, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_21)
        self.label_39.setGeometry(QtCore.QRect(10, 42, 21, 20))
        self.label_39.setObjectName("label_39")
        self.ed_eq_unusual = QtWidgets.QLineEdit(self.groupBox_21)
        self.ed_eq_unusual.setGeometry(QtCore.QRect(10, 120, 181, 21))
        self.ed_eq_unusual.setObjectName("ed_eq_unusual")
        self.label_40 = QtWidgets.QLabel(self.groupBox_21)
        self.label_40.setGeometry(QtCore.QRect(10, 140, 201, 16))
        self.label_40.setObjectName("label_40")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_22.setGeometry(QtCore.QRect(450, 0, 251, 371))
        self.groupBox_22.setObjectName("groupBox_22")
        self.cb_repair_2 = QtWidgets.QCheckBox(self.groupBox_22)
        self.cb_repair_2.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.cb_repair_2.setObjectName("cb_repair_2")
        self.cb_repair_time = QtWidgets.QCheckBox(self.groupBox_22)
        self.cb_repair_time.setGeometry(QtCore.QRect(10, 41, 91, 20))
        self.cb_repair_time.setObjectName("cb_repair_time")
        self.ed_repair_time = QtWidgets.QTimeEdit(self.groupBox_22)
        self.ed_repair_time.setGeometry(QtCore.QRect(60, 40, 61, 20))
        self.ed_repair_time.setObjectName("ed_repair_time")
        self.label_42 = QtWidgets.QLabel(self.groupBox_22)
        self.label_42.setGeometry(QtCore.QRect(120, 40, 72, 20))
        self.label_42.setObjectName("label_42")
        self.sw_mian.addWidget(self.page_6)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(660, 0, 71, 71))
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("icon/qun.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 10, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon/zfb.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/wx.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.bt_pay = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pay.setGeometry(QtCore.QRect(550, 40, 91, 23))
        self.bt_pay.setObjectName("bt_pay")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(550, 10, 31, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("icon/hbicon.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        Frame_main.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Frame_main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 748, 23))
        self.menuBar.setObjectName("menuBar")
        Frame_main.setMenuBar(self.menuBar)

        self.retranslateUi(Frame_main)
        self.sw_mian.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.af.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Frame_main)

    def retranslateUi(self, Frame_main):
        _translate = QtCore.QCoreApplication.translate
        Frame_main.setWindowTitle(_translate("Frame_main", "护萌宝"))
        self.tv_shipNum.setText(_translate("Frame_main", "<html><head/><body><p>117/120</p></body></html>"))
        self.tv_oil.setText(_translate("Frame_main", "58093"))
        self.tv_ammo.setText(_translate("Frame_main", "70738"))
        self.tv_steel.setText(_translate("Frame_main", "326012"))
        self.tv_aluminium.setText(_translate("Frame_main", "44745"))
        self.tv_fastRepair.setText(_translate("Frame_main", "368"))
        self.tv_fleetName.setText(_translate("Frame_main", "第一舰队"))
        self.label_22.setText(_translate("Frame_main", "当前:"))
        self.tv_nowrw.setText(_translate("Frame_main", "<html><head/><body><p>正在初始化...</p></body></html>"))
        self.label_23.setText(_translate("Frame_main", "新增:"))
        self.bt_add_campaign.setText(_translate("Frame_main", "战役"))
        self.bt_add_pvp.setText(_translate("Frame_main", "演习"))
        self.bt_add_battle.setText(_translate("Frame_main", "出征"))
        self.cb_run.setText(_translate("Frame_main", "任务执行开关"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Frame_main", "任务"))
        self.tv_nowDeal.setText(_translate("Frame_main", "状态栏"))
        self.af.setTabText(self.af.indexOf(self.tab_5), _translate("Frame_main", "经典"))
        self.af.setTabText(self.af.indexOf(self.tab_6), _translate("Frame_main", "重要"))
        self.bt_getLog.setText(_translate("Frame_main", "导出日志"))
        self.af.setTabText(self.af.indexOf(self.tab_7), _translate("Frame_main", "详细"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Frame_main", "日志"))
        self.groupBox_5.setTitle(_translate("Frame_main", "总收入:"))
        item = self.tb_count.horizontalHeaderItem(0)
        item.setText(_translate("Frame_main", "项目"))
        item = self.tb_count.horizontalHeaderItem(1)
        item.setText(_translate("Frame_main", "数量"))
        item = self.tb_count.horizontalHeaderItem(2)
        item.setText(_translate("Frame_main", "项目"))
        item = self.tb_count.horizontalHeaderItem(3)
        item.setText(_translate("Frame_main", "数量"))
        self.bt_count_ship.setText(_translate("Frame_main", "出货统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Frame_main", "统计"))
        self.groupBox_19.setTitle(_translate("Frame_main", "出征设置"))
        self.cb_repair.setItemText(0, _translate("Frame_main", "中破停止"))
        self.cb_repair.setItemText(1, _translate("Frame_main", "大破停止"))
        self.cb_repair.setItemText(2, _translate("Frame_main", "中破修理"))
        self.cb_repair.setItemText(3, _translate("Frame_main", "大破修理"))
        self.cb_rank.setText(_translate("Frame_main", "上榜停止(击沉榜)"))
        self.cb_500stop.setText(_translate("Frame_main", "出500船停止"))
        self.label_4.setText(_translate("Frame_main", "全局:"))
        self.groupBox_3.setTitle(_translate("Frame_main", "空闲设置"))
        self.cb_free_explore.setText(_translate("Frame_main", "空闲时远征"))
        self.cb_free_shower.setText(_translate("Frame_main", "空闲时泡澡"))
        self.groupBox_4.setTitle(_translate("Frame_main", "其他功能"))
        self.cb_changeName.setText(_translate("Frame_main", "出船自动改名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Frame_main", "全局设置"))
        self.cb_dismantle.setTitle(_translate("Frame_main", "分解设置"))
        self.cb_d_dd.setText(_translate("Frame_main", "驱逐"))
        self.cb_d_cl.setText(_translate("Frame_main", "轻巡"))
        self.cb_d_ca.setText(_translate("Frame_main", "重巡"))
        self.cb_d_bb.setText(_translate("Frame_main", "战列"))
        self.cb_d_bc.setText(_translate("Frame_main", "战巡"))
        self.cb_d_cvl.setText(_translate("Frame_main", "轻母"))
        self.cb_d_cv.setText(_translate("Frame_main", "航母"))
        self.cb_d_equipment.setText(_translate("Frame_main", "卸装备"))
        self.cb_d_save.setItemText(0, _translate("Frame_main", "不保留"))
        self.cb_d_save.setItemText(1, _translate("Frame_main", "保留6星"))
        self.cb_d_save.setItemText(2, _translate("Frame_main", "保留5星"))
        self.cb_d_save.setItemText(3, _translate("Frame_main", "保留4星"))
        self.cb_d_save.setItemText(4, _translate("Frame_main", "保留3星"))
        self.cb_d_unusualShip.setText(_translate("Frame_main", "保留特定船只"))
        self.label_5.setText(_translate("Frame_main", "支持模糊匹配，使用-隔离"))
        self.label_6.setText(_translate("Frame_main", "例如：朱诺-亚特"))
        self.label_9.setText(_translate("Frame_main", "结果：朱诺，亚特兰大"))
        self.cb_strengthen.setTitle(_translate("Frame_main", "强化设置"))
        self.label.setText(_translate("Frame_main", "待强化船只:"))
        self.cb_s_f.setText(_translate("Frame_main", "火力"))
        self.cb_s_t.setText(_translate("Frame_main", "鱼雷"))
        self.cb_s_d.setText(_translate("Frame_main", "装甲"))
        self.cb_s_a.setText(_translate("Frame_main", "防空"))
        self.cb_s_unusualShip.setText(_translate("Frame_main", "保留特定船只"))
        self.label_11.setText(_translate("Frame_main", "支持模糊匹配，使用-隔离"))
        self.cb_s_save.setItemText(0, _translate("Frame_main", "不保留"))
        self.cb_s_save.setItemText(1, _translate("Frame_main", "保留6星"))
        self.cb_s_save.setItemText(2, _translate("Frame_main", "保留5星"))
        self.cb_s_save.setItemText(3, _translate("Frame_main", "保留4星"))
        self.cb_s_save.setItemText(4, _translate("Frame_main", "保留3星"))
        self.bt_add_qh.setText(_translate("Frame_main", "编辑"))
        self.bt_d_back.setText(_translate("Frame_main", "返回"))
        self.cb_build.setTitle(_translate("Frame_main", "建造"))
        self.label_26.setText(_translate("Frame_main", "支持模糊匹配，使用-隔离"))
        self.label_27.setText(_translate("Frame_main", "例如：朱诺-亚特"))
        self.cb_build_unusual.setText(_translate("Frame_main", "出特定船只停止"))
        self.label_28.setText(_translate("Frame_main", "油"))
        self.label_29.setText(_translate("Frame_main", "弹"))
        self.label_30.setText(_translate("Frame_main", "钢"))
        self.label_32.setText(_translate("Frame_main", "铝"))
        self.cb_build_time.setText(_translate("Frame_main", "超过"))
        self.label_24.setText(_translate("Frame_main", "小时使用快建"))
        self.groupBox_21.setTitle(_translate("Frame_main", "开发--未开放"))
        self.cb_eq.setText(_translate("Frame_main", "自动开发开关"))
        self.cb_eq_unusual.setText(_translate("Frame_main", "出特定船只停止"))
        self.label_33.setText(_translate("Frame_main", "使用快建"))
        self.cb_eq_time.setText(_translate("Frame_main", "超过"))
        self.label_34.setText(_translate("Frame_main", "钢"))
        self.label_35.setText(_translate("Frame_main", "弹"))
        self.label_37.setText(_translate("Frame_main", "例如：朱诺-亚特"))
        self.label_38.setText(_translate("Frame_main", "铝"))
        self.label_39.setText(_translate("Frame_main", "油"))
        self.label_40.setText(_translate("Frame_main", "支持模糊匹配，使用-隔离"))
        self.groupBox_22.setTitle(_translate("Frame_main", "修理--未开放"))
        self.cb_repair_2.setText(_translate("Frame_main", "自动修理开关"))
        self.cb_repair_time.setText(_translate("Frame_main", "超过"))
        self.label_42.setText(_translate("Frame_main", "使用快修"))
        self.bt_pay.setText(_translate("Frame_main", "支持作者"))

