# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_add_campaign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_add_campaign(object):
    def setupUi(self, Frame_add_campaign):
        Frame_add_campaign.setObjectName("Frame_add_campaign")
        Frame_add_campaign.resize(368, 176)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame_add_campaign.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Frame_add_campaign)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 181, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cb_cm_map = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_cm_map.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.cb_cm_map.setObjectName("cb_cm_map")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_map.addItem("")
        self.cb_cm_repair = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_cm_repair.setGeometry(QtCore.QRect(10, 60, 91, 22))
        self.cb_cm_repair.setObjectName("cb_cm_repair")
        self.cb_cm_repair.addItem("")
        self.cb_cm_repair.addItem("")
        self.cb_cm_repair.addItem("")
        self.cb_cm_repair.addItem("")
        self.cb_cm_night = QtWidgets.QCheckBox(self.groupBox_5)
        self.cb_cm_night.setGeometry(QtCore.QRect(110, 60, 61, 21))
        self.cb_cm_night.setObjectName("cb_cm_night")
        self.bt_cm_run = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_cm_run.setGeometry(QtCore.QRect(40, 120, 101, 28))
        self.bt_cm_run.setObjectName("bt_cm_run")
        self.cb_cm_format = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_cm_format.setGeometry(QtCore.QRect(110, 30, 61, 22))
        self.cb_cm_format.setObjectName("cb_cm_format")
        self.cb_cm_format.addItem("")
        self.cb_cm_format.addItem("")
        self.cb_cm_format.addItem("")
        self.cb_cm_format.addItem("")
        self.cb_cm_format.addItem("")
        self.cb_sl = QtWidgets.QCheckBox(self.groupBox_5)
        self.cb_sl.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.cb_sl.setObjectName("cb_sl")
        self.ed_times = QtWidgets.QSpinBox(self.groupBox_5)
        self.ed_times.setGeometry(QtCore.QRect(70, 90, 61, 22))
        self.ed_times.setMaximum(9999)
        self.ed_times.setProperty("value", 999)
        self.ed_times.setObjectName("ed_times")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(140, 90, 31, 21))
        self.label.setObjectName("label")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(200, 10, 161, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.rb_classical = QtWidgets.QRadioButton(self.groupBox_6)
        self.rb_classical.setGeometry(QtCore.QRect(10, 30, 115, 19))
        self.rb_classical.setObjectName("rb_classical")
        self.rb_timer = QtWidgets.QRadioButton(self.groupBox_6)
        self.rb_timer.setGeometry(QtCore.QRect(10, 50, 115, 19))
        self.rb_timer.setObjectName("rb_timer")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 72, 21))
        self.label_2.setObjectName("label_2")
        self.te_time_hour = QtWidgets.QSpinBox(self.groupBox_6)
        self.te_time_hour.setGeometry(QtCore.QRect(60, 80, 42, 22))
        self.te_time_hour.setMaximum(23)
        self.te_time_hour.setObjectName("te_time_hour")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(100, 80, 16, 21))
        self.label_13.setObjectName("label_13")
        self.te_time_minute = QtWidgets.QSpinBox(self.groupBox_6)
        self.te_time_minute.setGeometry(QtCore.QRect(110, 80, 42, 22))
        self.te_time_minute.setMaximum(59)
        self.te_time_minute.setProperty("value", 10)
        self.te_time_minute.setObjectName("te_time_minute")
        Frame_add_campaign.setCentralWidget(self.centralwidget)

        self.retranslateUi(Frame_add_campaign)
        QtCore.QMetaObject.connectSlotsByName(Frame_add_campaign)

    def retranslateUi(self, Frame_add_campaign):
        _translate = QtCore.QCoreApplication.translate
        Frame_add_campaign.setWindowTitle(_translate("Frame_add_campaign", "战役设置"))
        self.groupBox_5.setTitle(_translate("Frame_add_campaign", "战役"))
        self.cb_cm_map.setItemText(0, _translate("Frame_add_campaign", "驱逐简单"))
        self.cb_cm_map.setItemText(1, _translate("Frame_add_campaign", "驱逐困难"))
        self.cb_cm_map.setItemText(2, _translate("Frame_add_campaign", "巡洋简单"))
        self.cb_cm_map.setItemText(3, _translate("Frame_add_campaign", "巡洋困难"))
        self.cb_cm_map.setItemText(4, _translate("Frame_add_campaign", "战列简单"))
        self.cb_cm_map.setItemText(5, _translate("Frame_add_campaign", "战列困难"))
        self.cb_cm_map.setItemText(6, _translate("Frame_add_campaign", "航母简单"))
        self.cb_cm_map.setItemText(7, _translate("Frame_add_campaign", "航母困难"))
        self.cb_cm_map.setItemText(8, _translate("Frame_add_campaign", "潜艇简单"))
        self.cb_cm_map.setItemText(9, _translate("Frame_add_campaign", "潜艇困难"))
        self.cb_cm_repair.setItemText(0, _translate("Frame_add_campaign", "中破修理"))
        self.cb_cm_repair.setItemText(1, _translate("Frame_add_campaign", "大破修理"))
        self.cb_cm_repair.setItemText(2, _translate("Frame_add_campaign", "中破停止"))
        self.cb_cm_repair.setItemText(3, _translate("Frame_add_campaign", "大破停止"))
        self.cb_cm_night.setText(_translate("Frame_add_campaign", "夜战"))
        self.bt_cm_run.setText(_translate("Frame_add_campaign", "添加任务"))
        self.cb_cm_format.setItemText(0, _translate("Frame_add_campaign", "单纵"))
        self.cb_cm_format.setItemText(1, _translate("Frame_add_campaign", "复纵"))
        self.cb_cm_format.setItemText(2, _translate("Frame_add_campaign", "轮型"))
        self.cb_cm_format.setItemText(3, _translate("Frame_add_campaign", "梯形"))
        self.cb_cm_format.setItemText(4, _translate("Frame_add_campaign", "单横"))
        self.cb_sl.setText(_translate("Frame_add_campaign", "无限SL"))
        self.label.setText(_translate("Frame_add_campaign", "次"))
        self.groupBox_6.setTitle(_translate("Frame_add_campaign", "类型"))
        self.rb_classical.setText(_translate("Frame_add_campaign", "作为经典任务"))
        self.rb_timer.setText(_translate("Frame_add_campaign", "作为定时任务"))
        self.label_2.setText(_translate("Frame_add_campaign", "开始时间:"))
        self.label_13.setText(_translate("Frame_add_campaign", " :"))

