# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_add_battle.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_add_battle(object):
    def setupUi(self, Frame_add_battle):
        Frame_add_battle.setObjectName("Frame_add_battle")
        Frame_add_battle.resize(719, 426)
        Frame_add_battle.setMinimumSize(QtCore.QSize(605, 324))
        Frame_add_battle.setMaximumSize(QtCore.QSize(9999, 9999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame_add_battle.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Frame_add_battle)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_SetRw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_SetRw.setGeometry(QtCore.QRect(340, 10, 21, 21))
        self.bt_SetRw.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_SetRw.setIcon(icon1)
        self.bt_SetRw.setObjectName("bt_SetRw")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_23.setObjectName("label_23")
        self.cb_rw = QtWidgets.QComboBox(self.centralwidget)
        self.cb_rw.setGeometry(QtCore.QRect(60, 10, 271, 21))
        self.cb_rw.setObjectName("cb_rw")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 41, 72, 20))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 41, 21))
        self.label_9.setObjectName("label_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 181, 81))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.rb_classical = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_classical.setGeometry(QtCore.QRect(10, 10, 115, 19))
        self.rb_classical.setObjectName("rb_classical")
        self.rb_timer = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_timer.setGeometry(QtCore.QRect(10, 30, 115, 19))
        self.rb_timer.setObjectName("rb_timer")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 72, 21))
        self.label_2.setObjectName("label_2")
        self.te_time_hour = QtWidgets.QSpinBox(self.groupBox_5)
        self.te_time_hour.setGeometry(QtCore.QRect(70, 50, 42, 22))
        self.te_time_hour.setMaximum(23)
        self.te_time_hour.setObjectName("te_time_hour")
        self.te_time_minute = QtWidgets.QSpinBox(self.groupBox_5)
        self.te_time_minute.setGeometry(QtCore.QRect(120, 50, 42, 22))
        self.te_time_minute.setMaximum(59)
        self.te_time_minute.setObjectName("te_time_minute")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(110, 50, 21, 21))
        self.label_13.setObjectName("label_13")
        self.ed_startNum = QtWidgets.QSpinBox(self.centralwidget)
        self.ed_startNum.setGeometry(QtCore.QRect(90, 40, 101, 22))
        self.ed_startNum.setMaximum(9999)
        self.ed_startNum.setProperty("value", 500)
        self.ed_startNum.setObjectName("ed_startNum")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 351, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 351, 16))
        self.label_4.setObjectName("label_4")
        self.cb_fleet = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fleet.setGeometry(QtCore.QRect(40, 70, 151, 22))
        self.cb_fleet.setObjectName("cb_fleet")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setGeometry(QtCore.QRect(130, 370, 93, 28))
        self.bt_start.setObjectName("bt_start")
        self.lt_fleet = QtWidgets.QListWidget(self.centralwidget)
        self.lt_fleet.setGeometry(QtCore.QRect(200, 40, 161, 171))
        self.lt_fleet.setObjectName("lt_fleet")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(370, 10, 341, 311))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 46, 31, 21))
        self.label_6.setObjectName("label_6")
        self.rb_fast_repair = QtWidgets.QRadioButton(self.groupBox)
        self.rb_fast_repair.setGeometry(QtCore.QRect(130, 20, 51, 21))
        self.rb_fast_repair.setObjectName("rb_fast_repair")
        self.rb_repair = QtWidgets.QRadioButton(self.groupBox)
        self.rb_repair.setGeometry(QtCore.QRect(190, 20, 51, 21))
        self.rb_repair.setObjectName("rb_repair")
        self.rb_change = QtWidgets.QRadioButton(self.groupBox)
        self.rb_change.setGeometry(QtCore.QRect(250, 20, 51, 21))
        self.rb_change.setObjectName("rb_change")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(40, 19, 69, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.label_5.setObjectName("label_5")
        self.cb_1 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_1.setGeometry(QtCore.QRect(40, 50, 51, 16))
        self.cb_1.setObjectName("cb_1")
        self.cb_2 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_2.setGeometry(QtCore.QRect(90, 50, 51, 16))
        self.cb_2.setObjectName("cb_2")
        self.cb_3 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_3.setGeometry(QtCore.QRect(140, 50, 51, 16))
        self.cb_3.setObjectName("cb_3")
        self.cb_4 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_4.setGeometry(QtCore.QRect(190, 50, 51, 16))
        self.cb_4.setObjectName("cb_4")
        self.cb_5 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_5.setGeometry(QtCore.QRect(240, 50, 51, 16))
        self.cb_5.setObjectName("cb_5")
        self.cb_6 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_6.setGeometry(QtCore.QRect(290, 50, 51, 16))
        self.cb_6.setObjectName("cb_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 321, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_repair_time = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_repair_time.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.cb_repair_time.setObjectName("cb_repair_time")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(120, 20, 181, 21))
        self.label_7.setObjectName("label_7")
        self.ed_repairMaxTime = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ed_repairMaxTime.setGeometry(QtCore.QRect(60, 20, 62, 22))
        self.ed_repairMaxTime.setObjectName("ed_repairMaxTime")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 321, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb_random_change = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_random_change.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.rb_random_change.setObjectName("rb_random_change")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 31, 21))
        self.label_8.setObjectName("label_8")
        self.ed_level_min = QtWidgets.QSpinBox(self.groupBox_3)
        self.ed_level_min.setGeometry(QtCore.QRect(40, 70, 42, 21))
        self.ed_level_min.setMinimum(1)
        self.ed_level_min.setMaximum(110)
        self.ed_level_min.setObjectName("ed_level_min")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(80, 70, 20, 21))
        self.label_10.setObjectName("label_10")
        self.ed_level_max = QtWidgets.QSpinBox(self.groupBox_3)
        self.ed_level_max.setGeometry(QtCore.QRect(100, 70, 42, 21))
        self.ed_level_max.setMinimum(1)
        self.ed_level_max.setMaximum(110)
        self.ed_level_max.setProperty("value", 110)
        self.ed_level_max.setObjectName("ed_level_max")
        self.rb_arrow_change = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_arrow_change.setGeometry(QtCore.QRect(160, 50, 71, 21))
        self.rb_arrow_change.setObjectName("rb_arrow_change")
        self.bt_ship_del = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_ship_del.setGeometry(QtCore.QRect(290, 50, 21, 20))
        self.bt_ship_del.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_ship_del.setIcon(icon2)
        self.bt_ship_del.setObjectName("bt_ship_del")
        self.bt_ship_add = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_ship_add.setGeometry(QtCore.QRect(270, 50, 21, 20))
        self.bt_ship_add.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_ship_add.setIcon(icon3)
        self.bt_ship_add.setObjectName("bt_ship_add")
        self.cb_equipment = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_equipment.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.cb_equipment.setObjectName("cb_equipment")
        self.lt_ship = QtWidgets.QListWidget(self.groupBox_3)
        self.lt_ship.setGeometry(QtCore.QRect(160, 70, 151, 91))
        self.lt_ship.setObjectName("lt_ship")
        self.cb_only_g = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_only_g.setGeometry(QtCore.QRect(10, 100, 131, 16))
        self.cb_only_g.setObjectName("cb_only_g")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 320, 341, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.bt_rule_add = QtWidgets.QPushButton(self.groupBox_4)
        self.bt_rule_add.setGeometry(QtCore.QRect(310, 20, 21, 21))
        self.bt_rule_add.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_rule_add.setIcon(icon4)
        self.bt_rule_add.setObjectName("bt_rule_add")
        self.bt_rule_del = QtWidgets.QPushButton(self.groupBox_4)
        self.bt_rule_del.setGeometry(QtCore.QRect(310, 70, 21, 23))
        self.bt_rule_del.setText("")
        self.bt_rule_del.setIcon(icon2)
        self.bt_rule_del.setObjectName("bt_rule_del")
        self.lt_rule = QtWidgets.QListWidget(self.groupBox_4)
        self.lt_rule.setGeometry(QtCore.QRect(10, 20, 301, 71))
        self.lt_rule.setObjectName("lt_rule")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 340, 351, 16))
        self.label_11.setObjectName("label_11")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 210, 351, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.cb_specialShip = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_specialShip.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.cb_specialShip.setObjectName("cb_specialShip")
        self.ed_specialShip = QtWidgets.QLineEdit(self.groupBox_6)
        self.ed_specialShip.setGeometry(QtCore.QRect(80, 20, 261, 20))
        self.ed_specialShip.setObjectName("ed_specialShip")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(10, 46, 331, 20))
        self.label_12.setObjectName("label_12")
        self.bt_re = QtWidgets.QPushButton(self.centralwidget)
        self.bt_re.setGeometry(QtCore.QRect(10, 100, 91, 21))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/jz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_re.setIcon(icon5)
        self.bt_re.setObjectName("bt_re")
        self.bt_setFleet = QtWidgets.QPushButton(self.centralwidget)
        self.bt_setFleet.setGeometry(QtCore.QRect(100, 100, 91, 21))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/repair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_setFleet.setIcon(icon6)
        self.bt_setFleet.setObjectName("bt_setFleet")
        Frame_add_battle.setCentralWidget(self.centralwidget)

        self.retranslateUi(Frame_add_battle)
        QtCore.QMetaObject.connectSlotsByName(Frame_add_battle)

    def retranslateUi(self, Frame_add_battle):
        _translate = QtCore.QCoreApplication.translate
        Frame_add_battle.setWindowTitle(_translate("Frame_add_battle", "添加出征任务"))
        self.label_23.setText(_translate("Frame_add_battle", "任务："))
        self.label.setText(_translate("Frame_add_battle", "执行次数："))
        self.label_9.setText(_translate("Frame_add_battle", "队伍:"))
        self.rb_classical.setText(_translate("Frame_add_battle", "作为经典任务"))
        self.rb_timer.setText(_translate("Frame_add_battle", "作为定时任务"))
        self.label_2.setText(_translate("Frame_add_battle", "开始时间:"))
        self.label_13.setText(_translate("Frame_add_battle", " :"))
        self.label_3.setText(_translate("Frame_add_battle", "经典任务:按顺序执行"))
        self.label_4.setText(_translate("Frame_add_battle", "定时任务:规定时间自动添加经典任务"))
        self.cb_fleet.setItemText(0, _translate("Frame_add_battle", "一队"))
        self.cb_fleet.setItemText(1, _translate("Frame_add_battle", "二队"))
        self.cb_fleet.setItemText(2, _translate("Frame_add_battle", "三队"))
        self.cb_fleet.setItemText(3, _translate("Frame_add_battle", "四队"))
        self.bt_start.setText(_translate("Frame_add_battle", "确定"))
        self.groupBox.setTitle(_translate("Frame_add_battle", "高级修理规则  --- 泡澡和换船目前有bug,不建议使用"))
        self.label_6.setText(_translate("Frame_add_battle", "生效:"))
        self.rb_fast_repair.setText(_translate("Frame_add_battle", "快修"))
        self.rb_repair.setText(_translate("Frame_add_battle", "泡澡"))
        self.rb_change.setText(_translate("Frame_add_battle", "更换"))
        self.comboBox.setItemText(0, _translate("Frame_add_battle", "全局"))
        self.comboBox.setItemText(1, _translate("Frame_add_battle", "中破"))
        self.comboBox.setItemText(2, _translate("Frame_add_battle", "大破"))
        self.label_5.setText(_translate("Frame_add_battle", "判定:"))
        self.cb_1.setText(_translate("Frame_add_battle", "位1"))
        self.cb_2.setText(_translate("Frame_add_battle", "位2"))
        self.cb_3.setText(_translate("Frame_add_battle", "位3"))
        self.cb_4.setText(_translate("Frame_add_battle", "位4"))
        self.cb_5.setText(_translate("Frame_add_battle", "位5"))
        self.cb_6.setText(_translate("Frame_add_battle", "位6"))
        self.groupBox_2.setTitle(_translate("Frame_add_battle", "泡澡设置"))
        self.cb_repair_time.setText(_translate("Frame_add_battle", "阈值:"))
        self.label_7.setText(_translate("Frame_add_battle", "(小时)  超过阈值将会使用快修"))
        self.groupBox_3.setTitle(_translate("Frame_add_battle", "换船设置"))
        self.rb_random_change.setText(_translate("Frame_add_battle", "模糊匹配"))
        self.label_8.setText(_translate("Frame_add_battle", "等级:"))
        self.label_10.setText(_translate("Frame_add_battle", " 到"))
        self.rb_arrow_change.setText(_translate("Frame_add_battle", "精确匹配"))
        self.cb_equipment.setText(_translate("Frame_add_battle", "自动更换装备"))
        self.cb_only_g.setText(_translate("Frame_add_battle", "仅匹配改装船只"))
        self.groupBox_4.setTitle(_translate("Frame_add_battle", "规则列表"))
        self.label_11.setText(_translate("Frame_add_battle", "允许制定多个修理规则"))
        self.groupBox_6.setTitle(_translate("Frame_add_battle", "其他功能:"))
        self.cb_specialShip.setText(_translate("Frame_add_battle", "出船停止:"))
        self.label_12.setText(_translate("Frame_add_battle", "模糊匹配,使用 - 分割"))
        self.bt_re.setText(_translate("Frame_add_battle", "编队"))
        self.bt_setFleet.setText(_translate("Frame_add_battle", "预设"))

