# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_add_pvp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_add_pvp(object):
    def setupUi(self, Frame_add_pvp):
        Frame_add_pvp.setObjectName("Frame_add_pvp")
        Frame_add_pvp.resize(757, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame_add_pvp.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Frame_add_pvp)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 10, 72, 21))
        self.label_2.setObjectName("label_2")
        self.rb_classical = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_classical.setGeometry(QtCore.QRect(10, 10, 115, 19))
        self.rb_classical.setObjectName("rb_classical")
        self.groupBox_17 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(570, 40, 181, 451))
        self.groupBox_17.setObjectName("groupBox_17")
        self.cb_pvp_night = QtWidgets.QCheckBox(self.groupBox_17)
        self.cb_pvp_night.setGeometry(QtCore.QRect(10, 200, 61, 21))
        self.cb_pvp_night.setObjectName("cb_pvp_night")
        self.cb_pvp_cv = QtWidgets.QCheckBox(self.groupBox_17)
        self.cb_pvp_cv.setGeometry(QtCore.QRect(10, 230, 121, 19))
        self.cb_pvp_cv.setObjectName("cb_pvp_cv")
        self.cb_pvp_ss = QtWidgets.QCheckBox(self.groupBox_17)
        self.cb_pvp_ss.setGeometry(QtCore.QRect(10, 260, 121, 19))
        self.cb_pvp_ss.setObjectName("cb_pvp_ss")
        self.bt_pvp_run = QtWidgets.QPushButton(self.groupBox_17)
        self.bt_pvp_run.setGeometry(QtCore.QRect(40, 310, 101, 28))
        self.bt_pvp_run.setObjectName("bt_pvp_run")
        self.cb_pvp_format = QtWidgets.QComboBox(self.groupBox_17)
        self.cb_pvp_format.setGeometry(QtCore.QRect(80, 200, 61, 21))
        self.cb_pvp_format.setObjectName("cb_pvp_format")
        self.cb_pvp_format.addItem("")
        self.cb_pvp_format.addItem("")
        self.cb_pvp_format.addItem("")
        self.cb_pvp_format.addItem("")
        self.cb_pvp_format.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox_17)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_9.setObjectName("label_9")
        self.cb_fleet = QtWidgets.QComboBox(self.groupBox_17)
        self.cb_fleet.setGeometry(QtCore.QRect(50, 20, 121, 22))
        self.cb_fleet.setObjectName("cb_fleet")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.lt_fleet = QtWidgets.QListWidget(self.groupBox_17)
        self.lt_fleet.setGeometry(QtCore.QRect(10, 50, 161, 141))
        self.lt_fleet.setObjectName("lt_fleet")
        self.rb_timer = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_timer.setGeometry(QtCore.QRect(140, 10, 115, 19))
        self.rb_timer.setObjectName("rb_timer")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 551, 451))
        self.groupBox.setObjectName("groupBox")
        self.lt_pvp = QtWidgets.QListWidget(self.groupBox)
        self.lt_pvp.setGeometry(QtCore.QRect(10, 20, 521, 421))
        self.lt_pvp.setObjectName("lt_pvp")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 10, 21, 21))
        self.label_13.setObjectName("label_13")
        self.te_time_minute = QtWidgets.QSpinBox(self.centralwidget)
        self.te_time_minute.setGeometry(QtCore.QRect(370, 10, 42, 22))
        self.te_time_minute.setMaximum(59)
        self.te_time_minute.setObjectName("te_time_minute")
        self.te_time_hour = QtWidgets.QSpinBox(self.centralwidget)
        self.te_time_hour.setGeometry(QtCore.QRect(320, 10, 42, 22))
        self.te_time_hour.setMaximum(23)
        self.te_time_hour.setObjectName("te_time_hour")
        Frame_add_pvp.setCentralWidget(self.centralwidget)

        self.retranslateUi(Frame_add_pvp)
        QtCore.QMetaObject.connectSlotsByName(Frame_add_pvp)

    def retranslateUi(self, Frame_add_pvp):
        _translate = QtCore.QCoreApplication.translate
        Frame_add_pvp.setWindowTitle(_translate("Frame_add_pvp", "演习设置"))
        self.label_2.setText(_translate("Frame_add_pvp", "开始时间:"))
        self.rb_classical.setText(_translate("Frame_add_pvp", "作为经典任务"))
        self.groupBox_17.setTitle(_translate("Frame_add_pvp", "演习"))
        self.cb_pvp_night.setText(_translate("Frame_add_pvp", "夜战"))
        self.cb_pvp_cv.setText(_translate("Frame_add_pvp", "遇航母变轮型"))
        self.cb_pvp_ss.setText(_translate("Frame_add_pvp", "遇潜艇变单横"))
        self.bt_pvp_run.setText(_translate("Frame_add_pvp", "添加任务"))
        self.cb_pvp_format.setItemText(0, _translate("Frame_add_pvp", "单纵"))
        self.cb_pvp_format.setItemText(1, _translate("Frame_add_pvp", "复纵"))
        self.cb_pvp_format.setItemText(2, _translate("Frame_add_pvp", "轮型"))
        self.cb_pvp_format.setItemText(3, _translate("Frame_add_pvp", "梯形"))
        self.cb_pvp_format.setItemText(4, _translate("Frame_add_pvp", "单横"))
        self.label_9.setText(_translate("Frame_add_pvp", "队伍:"))
        self.cb_fleet.setItemText(0, _translate("Frame_add_pvp", "一队"))
        self.cb_fleet.setItemText(1, _translate("Frame_add_pvp", "二队"))
        self.cb_fleet.setItemText(2, _translate("Frame_add_pvp", "三队"))
        self.cb_fleet.setItemText(3, _translate("Frame_add_pvp", "四队"))
        self.rb_timer.setText(_translate("Frame_add_pvp", "作为定时任务"))
        self.groupBox.setTitle(_translate("Frame_add_pvp", "对手"))
        self.label_13.setText(_translate("Frame_add_pvp", " :"))

