# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_user_fleet.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserFleet(object):
    def setupUi(self, UserFleet):
        UserFleet.setObjectName("UserFleet")
        UserFleet.resize(509, 344)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserFleet.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(UserFleet)
        self.centralwidget.setObjectName("centralwidget")
        self.lt_fleetList = QtWidgets.QListWidget(self.centralwidget)
        self.lt_fleetList.setGeometry(QtCore.QRect(10, 30, 201, 311))
        self.lt_fleetList.setObjectName("lt_fleetList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 201, 31))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 30, 211, 311))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_2.setObjectName("label_2")
        self.ed_name = QtWidgets.QLineEdit(self.groupBox)
        self.ed_name.setGeometry(QtCore.QRect(50, 10, 151, 21))
        self.ed_name.setObjectName("ed_name")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_3.setObjectName("label_3")
        self.cb_fleet = QtWidgets.QComboBox(self.groupBox)
        self.cb_fleet.setGeometry(QtCore.QRect(70, 40, 131, 22))
        self.cb_fleet.setObjectName("cb_fleet")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.cb_fleet.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_4.setObjectName("label_4")
        self.lt_fleetMember = QtWidgets.QListWidget(self.groupBox)
        self.lt_fleetMember.setGeometry(QtCore.QRect(10, 90, 191, 211))
        self.lt_fleetMember.setObjectName("lt_fleetMember")
        self.bt_editFleet = QtWidgets.QPushButton(self.groupBox)
        self.bt_editFleet.setGeometry(QtCore.QRect(160, 270, 31, 23))
        self.bt_editFleet.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/jz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_editFleet.setIcon(icon1)
        self.bt_editFleet.setObjectName("bt_editFleet")
        self.bt_read = QtWidgets.QPushButton(self.centralwidget)
        self.bt_read.setGeometry(QtCore.QRect(220, 80, 61, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_read.setIcon(icon2)
        self.bt_read.setObjectName("bt_read")
        self.bt_write = QtWidgets.QPushButton(self.centralwidget)
        self.bt_write.setGeometry(QtCore.QRect(220, 260, 61, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_write.setIcon(icon3)
        self.bt_write.setObjectName("bt_write")
        self.bt_del = QtWidgets.QPushButton(self.centralwidget)
        self.bt_del.setGeometry(QtCore.QRect(220, 170, 61, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_del.setIcon(icon4)
        self.bt_del.setObjectName("bt_del")
        UserFleet.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserFleet)
        QtCore.QMetaObject.connectSlotsByName(UserFleet)

    def retranslateUi(self, UserFleet):
        _translate = QtCore.QCoreApplication.translate
        UserFleet.setWindowTitle(_translate("UserFleet", "自定义队伍"))
        self.label.setText(_translate("UserFleet", "自定义队伍列表:"))
        self.label_2.setText(_translate("UserFleet", "名称:"))
        self.label_3.setText(_translate("UserFleet", "生效队伍:"))
        self.cb_fleet.setItemText(0, _translate("UserFleet", "一队"))
        self.cb_fleet.setItemText(1, _translate("UserFleet", "二队"))
        self.cb_fleet.setItemText(2, _translate("UserFleet", "三队"))
        self.cb_fleet.setItemText(3, _translate("UserFleet", "四队"))
        self.label_4.setText(_translate("UserFleet", "队伍成员:"))
        self.bt_read.setText(_translate("UserFleet", "读取"))
        self.bt_write.setText(_translate("UserFleet", "写入"))
        self.bt_del.setText(_translate("UserFleet", "删除"))

