# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_select_ship.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_select_ship(object):
    def setupUi(self, Frame_select_ship):
        Frame_select_ship.setObjectName("Frame_select_ship")
        Frame_select_ship.resize(515, 581)
        self.buttonBox = QtWidgets.QDialogButtonBox(Frame_select_ship)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Frame_select_ship)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Frame_select_ship)
        self.groupBox.setGeometry(QtCore.QRect(290, 20, 211, 131))
        self.groupBox.setObjectName("groupBox")
        self.cb_level = QtWidgets.QCheckBox(self.groupBox)
        self.cb_level.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.cb_level.setObjectName("cb_level")
        self.cb_level_min = QtWidgets.QSpinBox(self.groupBox)
        self.cb_level_min.setGeometry(QtCore.QRect(60, 27, 42, 20))
        self.cb_level_min.setMinimum(1)
        self.cb_level_min.setMaximum(110)
        self.cb_level_min.setObjectName("cb_level_min")
        self.cb_level_max = QtWidgets.QSpinBox(self.groupBox)
        self.cb_level_max.setGeometry(QtCore.QRect(130, 27, 42, 20))
        self.cb_level_max.setMinimum(1)
        self.cb_level_max.setMaximum(110)
        self.cb_level_max.setObjectName("cb_level_max")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 21, 16))
        self.label_2.setObjectName("label_2")
        self.cb_type = QtWidgets.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(60, 60, 111, 22))
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 54, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 41, 21))
        self.label_4.setObjectName("label_4")
        self.ed_name = QtWidgets.QLineEdit(self.groupBox)
        self.ed_name.setGeometry(QtCore.QRect(60, 100, 113, 20))
        self.ed_name.setObjectName("ed_name")
        self.lt_select_ship = QtWidgets.QListWidget(Frame_select_ship)
        self.lt_select_ship.setGeometry(QtCore.QRect(290, 160, 211, 371))
        self.lt_select_ship.setObjectName("lt_select_ship")
        self.lt_all_ship = QtWidgets.QListWidget(Frame_select_ship)
        self.lt_all_ship.setGeometry(QtCore.QRect(10, 30, 261, 501))
        self.lt_all_ship.setObjectName("lt_all_ship")

        self.retranslateUi(Frame_select_ship)
        self.buttonBox.accepted.connect(Frame_select_ship.accept)
        self.buttonBox.rejected.connect(Frame_select_ship.reject)
        QtCore.QMetaObject.connectSlotsByName(Frame_select_ship)

    def retranslateUi(self, Frame_select_ship):
        _translate = QtCore.QCoreApplication.translate
        Frame_select_ship.setWindowTitle(_translate("Frame_select_ship", "Dialog"))
        self.label.setText(_translate("Frame_select_ship", "双击船只添加,单击添加列表删除"))
        self.groupBox.setTitle(_translate("Frame_select_ship", "筛选条件"))
        self.cb_level.setText(_translate("Frame_select_ship", "等级:"))
        self.label_2.setText(_translate("Frame_select_ship", "到"))
        self.cb_type.setItemText(0, _translate("Frame_select_ship", "全部"))
        self.cb_type.setItemText(1, _translate("Frame_select_ship", "航母"))
        self.cb_type.setItemText(2, _translate("Frame_select_ship", "轻母"))
        self.cb_type.setItemText(3, _translate("Frame_select_ship", "装母"))
        self.cb_type.setItemText(4, _translate("Frame_select_ship", "战列"))
        self.cb_type.setItemText(5, _translate("Frame_select_ship", "航战"))
        self.cb_type.setItemText(6, _translate("Frame_select_ship", "战巡"))
        self.cb_type.setItemText(7, _translate("Frame_select_ship", "重巡"))
        self.cb_type.setItemText(8, _translate("Frame_select_ship", "航巡"))
        self.cb_type.setItemText(9, _translate("Frame_select_ship", "雷巡"))
        self.cb_type.setItemText(10, _translate("Frame_select_ship", "轻巡"))
        self.cb_type.setItemText(11, _translate("Frame_select_ship", "重炮"))
        self.cb_type.setItemText(12, _translate("Frame_select_ship", "驱逐"))
        self.cb_type.setItemText(13, _translate("Frame_select_ship", "潜母"))
        self.cb_type.setItemText(14, _translate("Frame_select_ship", "潜艇"))
        self.cb_type.setItemText(15, _translate("Frame_select_ship", "炮潜"))
        self.cb_type.setItemText(16, _translate("Frame_select_ship", "补给"))
        self.cb_type.setItemText(17, _translate("Frame_select_ship", "导驱"))
        self.cb_type.setItemText(18, _translate("Frame_select_ship", "防驱"))
        self.cb_type.setItemText(19, _translate("Frame_select_ship", "其他"))
        self.label_3.setText(_translate("Frame_select_ship", "类型:"))
        self.label_4.setText(_translate("Frame_select_ship", "名称:"))

