# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_rw.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_Rw(object):
    def setupUi(self, Frame_Rw):
        Frame_Rw.setObjectName("Frame_Rw")
        Frame_Rw.resize(654, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame_Rw.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Frame_Rw)
        self.centralwidget.setObjectName("centralwidget")
        self.list_Rw = QtWidgets.QListWidget(self.centralwidget)
        self.list_Rw.setGeometry(QtCore.QRect(10, 30, 161, 471))
        self.list_Rw.setObjectName("list_Rw")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.bt_readRw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_readRw.setGeometry(QtCore.QRect(180, 90, 21, 21))
        self.bt_readRw.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_readRw.setIcon(icon1)
        self.bt_readRw.setObjectName("bt_readRw")
        self.bt_saveRw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_saveRw.setGeometry(QtCore.QRect(180, 380, 21, 21))
        self.bt_saveRw.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_saveRw.setIcon(icon2)
        self.bt_saveRw.setObjectName("bt_saveRw")
        self.bt_delRw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_delRw.setGeometry(QtCore.QRect(180, 240, 21, 21))
        self.bt_delRw.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_delRw.setIcon(icon3)
        self.bt_delRw.setObjectName("bt_delRw")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(210, 30, 431, 471))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_2.setObjectName("label_2")
        self.cb_map = QtWidgets.QComboBox(self.groupBox)
        self.cb_map.setGeometry(QtCore.QRect(50, 11, 121, 21))
        self.cb_map.setObjectName("cb_map")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.cb_map.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(170, 10, 72, 21))
        self.label_3.setObjectName("label_3")
        self.ed_name = QtWidgets.QLineEdit(self.groupBox)
        self.ed_name.setGeometry(QtCore.QRect(240, 10, 181, 21))
        self.ed_name.setObjectName("ed_name")
        self.tv_map = QtWidgets.QLabel(self.groupBox)
        self.tv_map.setGeometry(QtCore.QRect(10, 40, 411, 221))
        self.tv_map.setText("")
        self.tv_map.setPixmap(QtGui.QPixmap("../../Users/Hasee/.designer/backup/icon/map26.png"))
        self.tv_map.setScaledContents(True)
        self.tv_map.setObjectName("tv_map")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 101, 21))
        self.label_5.setObjectName("label_5")
        self.ed_point = QtWidgets.QLineEdit(self.groupBox)
        self.ed_point.setGeometry(QtCore.QRect(110, 270, 311, 21))
        self.ed_point.setText("")
        self.ed_point.setObjectName("ed_point")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 411, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 15, 41, 21))
        self.label_6.setObjectName("label_6")
        self.cb_format = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_format.setGeometry(QtCore.QRect(50, 16, 131, 20))
        self.cb_format.setObjectName("cb_format")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 72, 21))
        self.label_7.setObjectName("label_7")
        self.cb_spyFail = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_spyFail.setGeometry(QtCore.QRect(80, 40, 101, 22))
        self.cb_spyFail.setObjectName("cb_spyFail")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_spyFail.addItem("")
        self.cb_skipDeal = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_skipDeal.setGeometry(QtCore.QRect(70, 65, 111, 20))
        self.cb_skipDeal.setObjectName("cb_skipDeal")
        self.cb_skipDeal.addItem("")
        self.cb_skipDeal.addItem("")
        self.cb_skipDeal.addItem("")
        self.cb_hmChange = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_hmChange.setGeometry(QtCore.QRect(210, 10, 121, 19))
        self.cb_hmChange.setObjectName("cb_hmChange")
        self.cb_qtChange = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_qtChange.setGeometry(QtCore.QRect(210, 50, 111, 19))
        self.cb_qtChange.setObjectName("cb_qtChange")
        self.cb_reward = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_reward.setGeometry(QtCore.QRect(210, 70, 151, 19))
        self.cb_reward.setObjectName("cb_reward")
        self.cb_skip = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_skip.setGeometry(QtCore.QRect(10, 68, 61, 16))
        self.cb_skip.setObjectName("cb_skip")
        self.cb_qmChange = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_qmChange.setGeometry(QtCore.QRect(210, 30, 121, 19))
        self.cb_qmChange.setObjectName("cb_qmChange")
        self.cb_nightFight = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_nightFight.setGeometry(QtCore.QRect(10, 90, 171, 19))
        self.cb_nightFight.setObjectName("cb_nightFight")
        self.cb_resource = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_resource.setGeometry(QtCore.QRect(210, 90, 91, 19))
        self.cb_resource.setObjectName("cb_resource")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 410, 411, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.bt_detail_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_1.setGeometry(QtCore.QRect(10, 20, 31, 28))
        self.bt_detail_1.setText("")
        self.bt_detail_1.setObjectName("bt_detail_1")
        self.bt_detail_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_2.setGeometry(QtCore.QRect(40, 20, 31, 28))
        self.bt_detail_2.setText("")
        self.bt_detail_2.setObjectName("bt_detail_2")
        self.bt_detail_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_3.setGeometry(QtCore.QRect(70, 20, 31, 28))
        self.bt_detail_3.setText("")
        self.bt_detail_3.setObjectName("bt_detail_3")
        self.bt_detail_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_4.setGeometry(QtCore.QRect(100, 20, 31, 28))
        self.bt_detail_4.setText("")
        self.bt_detail_4.setObjectName("bt_detail_4")
        self.bt_detail_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_5.setGeometry(QtCore.QRect(130, 20, 31, 28))
        self.bt_detail_5.setText("")
        self.bt_detail_5.setObjectName("bt_detail_5")
        self.bt_detail_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_6.setGeometry(QtCore.QRect(160, 20, 31, 28))
        self.bt_detail_6.setText("")
        self.bt_detail_6.setObjectName("bt_detail_6")
        self.bt_detail_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_7.setGeometry(QtCore.QRect(190, 20, 31, 28))
        self.bt_detail_7.setText("")
        self.bt_detail_7.setObjectName("bt_detail_7")
        self.bt_detail_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_8.setGeometry(QtCore.QRect(220, 20, 31, 28))
        self.bt_detail_8.setText("")
        self.bt_detail_8.setObjectName("bt_detail_8")
        self.bt_detail_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_9.setGeometry(QtCore.QRect(250, 20, 31, 28))
        self.bt_detail_9.setText("")
        self.bt_detail_9.setObjectName("bt_detail_9")
        self.bt_detail_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_10.setGeometry(QtCore.QRect(280, 20, 31, 28))
        self.bt_detail_10.setText("")
        self.bt_detail_10.setObjectName("bt_detail_10")
        self.bt_detail_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_11.setGeometry(QtCore.QRect(310, 20, 31, 28))
        self.bt_detail_11.setText("")
        self.bt_detail_11.setObjectName("bt_detail_11")
        self.bt_detail_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_12.setGeometry(QtCore.QRect(340, 20, 31, 28))
        self.bt_detail_12.setText("")
        self.bt_detail_12.setObjectName("bt_detail_12")
        self.bt_detail_13 = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_detail_13.setGeometry(QtCore.QRect(370, 20, 31, 28))
        self.bt_detail_13.setText("")
        self.bt_detail_13.setObjectName("bt_detail_13")
        Frame_Rw.setCentralWidget(self.centralwidget)

        self.retranslateUi(Frame_Rw)
        QtCore.QMetaObject.connectSlotsByName(Frame_Rw)

    def retranslateUi(self, Frame_Rw):
        _translate = QtCore.QCoreApplication.translate
        Frame_Rw.setWindowTitle(_translate("Frame_Rw", "任务设置"))
        self.label.setText(_translate("Frame_Rw", "任务列表："))
        self.label_2.setText(_translate("Frame_Rw", "地图："))
        self.cb_map.setItemText(0, _translate("Frame_Rw", "1-1"))
        self.cb_map.setItemText(1, _translate("Frame_Rw", "1-2"))
        self.cb_map.setItemText(2, _translate("Frame_Rw", "1-3"))
        self.cb_map.setItemText(3, _translate("Frame_Rw", "1-4"))
        self.cb_map.setItemText(4, _translate("Frame_Rw", "2-1"))
        self.cb_map.setItemText(5, _translate("Frame_Rw", "2-2"))
        self.cb_map.setItemText(6, _translate("Frame_Rw", "2-3"))
        self.cb_map.setItemText(7, _translate("Frame_Rw", "2-4"))
        self.cb_map.setItemText(8, _translate("Frame_Rw", "2-5"))
        self.cb_map.setItemText(9, _translate("Frame_Rw", "2-6"))
        self.cb_map.setItemText(10, _translate("Frame_Rw", "3-1"))
        self.cb_map.setItemText(11, _translate("Frame_Rw", "3-2"))
        self.cb_map.setItemText(12, _translate("Frame_Rw", "3-3"))
        self.cb_map.setItemText(13, _translate("Frame_Rw", "3-4"))
        self.cb_map.setItemText(14, _translate("Frame_Rw", "4-1"))
        self.cb_map.setItemText(15, _translate("Frame_Rw", "4-2"))
        self.cb_map.setItemText(16, _translate("Frame_Rw", "4-3"))
        self.cb_map.setItemText(17, _translate("Frame_Rw", "4-4"))
        self.cb_map.setItemText(18, _translate("Frame_Rw", "5-1"))
        self.cb_map.setItemText(19, _translate("Frame_Rw", "5-2"))
        self.cb_map.setItemText(20, _translate("Frame_Rw", "5-3"))
        self.cb_map.setItemText(21, _translate("Frame_Rw", "5-4"))
        self.cb_map.setItemText(22, _translate("Frame_Rw", "5-5"))
        self.cb_map.setItemText(23, _translate("Frame_Rw", "6-1"))
        self.cb_map.setItemText(24, _translate("Frame_Rw", "6-2"))
        self.cb_map.setItemText(25, _translate("Frame_Rw", "6-3"))
        self.cb_map.setItemText(26, _translate("Frame_Rw", "6-4"))
        self.cb_map.setItemText(27, _translate("Frame_Rw", "7-1"))
        self.cb_map.setItemText(28, _translate("Frame_Rw", "7-2"))
        self.cb_map.setItemText(29, _translate("Frame_Rw", "7-3"))
        self.cb_map.setItemText(30, _translate("Frame_Rw", "7-4"))
        self.cb_map.setItemText(31, _translate("Frame_Rw", "7-5"))
        self.cb_map.setItemText(32, _translate("Frame_Rw", "8-1"))
        self.cb_map.setItemText(33, _translate("Frame_Rw", "Ex-1"))
        self.cb_map.setItemText(34, _translate("Frame_Rw", "Ex-2"))
        self.cb_map.setItemText(35, _translate("Frame_Rw", "Ex-3"))
        self.cb_map.setItemText(36, _translate("Frame_Rw", "Ex-4"))
        self.cb_map.setItemText(37, _translate("Frame_Rw", "Ex-5"))
        self.cb_map.setItemText(38, _translate("Frame_Rw", "Ex-6"))
        self.cb_map.setItemText(39, _translate("Frame_Rw", "Ex-7"))
        self.cb_map.setItemText(40, _translate("Frame_Rw", "Ex-8"))
        self.cb_map.setItemText(41, _translate("Frame_Rw", "Ex-9"))
        self.cb_map.setItemText(42, _translate("Frame_Rw", "Ex-10"))
        self.label_3.setText(_translate("Frame_Rw", "配置名称："))
        self.label_5.setText(_translate("Frame_Rw", "经过点(无序):"))
        self.groupBox_2.setTitle(_translate("Frame_Rw", "全局配置(低优先级)"))
        self.label_6.setText(_translate("Frame_Rw", "阵形："))
        self.cb_format.setItemText(0, _translate("Frame_Rw", "单纵"))
        self.cb_format.setItemText(1, _translate("Frame_Rw", "复纵"))
        self.cb_format.setItemText(2, _translate("Frame_Rw", "轮型"))
        self.cb_format.setItemText(3, _translate("Frame_Rw", "梯形"))
        self.cb_format.setItemText(4, _translate("Frame_Rw", "单横"))
        self.label_7.setText(_translate("Frame_Rw", "索敌失败："))
        self.cb_spyFail.setItemText(0, _translate("Frame_Rw", "无动作"))
        self.cb_spyFail.setItemText(1, _translate("Frame_Rw", "SL"))
        self.cb_spyFail.setItemText(2, _translate("Frame_Rw", "单纵"))
        self.cb_spyFail.setItemText(3, _translate("Frame_Rw", "复纵"))
        self.cb_spyFail.setItemText(4, _translate("Frame_Rw", "轮型"))
        self.cb_spyFail.setItemText(5, _translate("Frame_Rw", "梯形"))
        self.cb_spyFail.setItemText(6, _translate("Frame_Rw", "单横"))
        self.cb_skipDeal.setItemText(0, _translate("Frame_Rw", "失败硬怼"))
        self.cb_skipDeal.setItemText(1, _translate("Frame_Rw", "一次SL"))
        self.cb_skipDeal.setItemText(2, _translate("Frame_Rw", "两次SL"))
        self.cb_hmChange.setText(_translate("Frame_Rw", "遇航母换轮型"))
        self.cb_qtChange.setText(_translate("Frame_Rw", "遇潜艇换单横"))
        self.cb_reward.setText(_translate("Frame_Rw", "迂回点战利品战斗"))
        self.cb_skip.setText(_translate("Frame_Rw", "迂回"))
        self.cb_qmChange.setText(_translate("Frame_Rw", "遇轻母换轮型"))
        self.cb_nightFight.setText(_translate("Frame_Rw", "全局夜战"))
        self.cb_resource.setText(_translate("Frame_Rw", "资源点SL"))
        self.groupBox_3.setTitle(_translate("Frame_Rw", "单独配置(高优先级)   --  阵容SL在这里"))

